### ISSUE TITLE
DevTools problem in SSR

### ISSUE THREAD

**Issue by pom421** [bluebill1049/little-state-machine#39]
Hello, 

I use LSM in Next.js and the `DevTool` component doesn't seem to work correctly.

Here is a sandbox: https://codesandbox.io/s/bug-next-littlestatemachine-f4cwq

The sandbox is working online, but when I download it and make `yarn` and `yarn dev`, you will normally see the problem.

The error log is

```
/Users/pom/Downloads/f4cwq/node_modules/little-state-machine-devtools/dist/index.js:1
import * as React from 'react';
       ^

SyntaxError: Unexpected token *
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/pom/Downloads/f4cwq/node_modules/little-state-machine-devtools/index.js:6:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.little-state-machine-devtools (/Users/pom/Downloads/f4cwq/.next/server/static/development/pages/_app.js:1544:18)
/Users/pom/Downloads/f4cwq/node_modules/little-state-machine-devtools/dist/index.js:1
```

This is a server side routing problem only, because if I comment the lines mentionning DevTool in the _app.js file and uncomment them, the DevTool will eventually work, but it will fail again at the next hard refresh causing a server side refresh.

So, I don't know why in server side, babel doesn't seem to transpile the `import * as React` in ES5 syntax of the DevTool module.

**Comment by pom421** [comment]
I troubleshoot a step further. 

After having installed `next-transpile-modules`, I have the DevTools which seems to compile.

My next.config.js is : 
```
const webpack = require("webpack")
const withPlugins = require("next-compose-plugins")
const withSourceMaps = require("@zeit/next-source-maps")
const withTM = require("next-transpile-modules")([
  "little-state-machine-devtools",
])

const nextConfig = {
  webpack: (config, { isServer, buildId }) => {
    config.plugins.push(
      new webpack.DefinePlugin({
        // looks like it doesnt work for some reason
        "process.env.SENTRY_RELEASE": JSON.stringify(buildId),
      }),
    )

    if (!isServer) {
      config.resolve.alias["@sentry/node"] = "@sentry/browser"
    }

    return config
  },
}

module.exports = withPlugins([[withSourceMaps], [withTM]], nextConfig)
```

Now I have another error

```
ReferenceError: window is not defined
    at DevTool (/Users/pom/workspace/onvs/.next/server/static/development/pages/_app.js:581:13)
    at processChild (/Users/pom/workspace/onvs/node_modules/react-dom/cjs/react-dom-server.node.development.js:3043:14)
```
It seems fair to not have window in server environement.

So DevTools doesn't seem to work in SSR environement. 
It's too bad, because after the first load, everything woking in client side essentially, DevTool is OK.

Is it planned to make it server side compatible ?

**Comment by bluebill1049** [comment]
hmmm we should make it work for SSR, I will take a look at it.

**Comment by bluebill1049** [comment]
is this caused by devtool or LSM?

**Comment by pom421** [comment]
Only DevTool, LSM doesn't make an error.

**Comment by bluebill1049** [comment]
oh i see.
