### ISSUE TITLE
Error on SSR projects with actions execution

### ISSUE THREAD

**Issue by dipiash** [bluebill1049/little-state-machine#45]
Now I see that source code in tag v3.0.2 (https://github.com/bluebill1049/little-state-machine/releases/tag/v3.0.2), doesn't contain changes for middleware.

In archive:
```
export const middleWare = (data: string = '') => {
  if (data) {
    // @ts-ignore
    window[STORE_ACTION_NAME] = data;
  }
  return data;
};
...
 if (isDevMode) {
    middleWare(debugName);
  }

...
```
and when I execute action on Server Side I have an error:
```
ReferenceError: window is not defined
    at middleWare (/ssr/node_modules/little-state-machine/dist/little-state-machine.js:125:9)
    at Object.updateUserData (/ssr/node_modules/little-state-machine/dist/little-state-machine.js:163:9)
```

**Comment by bluebill1049** [comment]
you happy to submit a PR on this?

**Comment by dipiash** [comment]
Yes I can

**Comment by dipiash** [comment]
Can you publish new version?

**Comment by bluebill1049** [comment]
done.
