### ISSUE TITLE
Disabling cookies in Chrome causes window.sessionStorage lookup to error

### ISSUE THREAD

**Issue by D1plo1d** [bluebill1049/little-state-machine#71]
It looks like the sessionStorage lookup needs to be wrapped in a try catch to allow for Chrome users with cookies disabled:

```
src.f69400ca.js:116 Uncaught DOMException: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.
    at new e (http://localhost:1234/src.f69400ca.js:11651:87)
    at Object.parcelRequire.../node_modules/little-state-machine/dist/little-state-machine.es.js.react (http://localhost:1234/src.f69400ca.js:11649:9)
    at newRequire (http://localhost:1234/src.f69400ca.js:47:24)
    at localRequire (http://localhost:1234/src.f69400ca.js:53:14)
    at Object.parcelRequire.index.tsx.core-js/modules/es6.array.copy-within (http://localhost:1234/src.f69400ca.js:108133:30)
    at newRequire (http://localhost:1234/src.f69400ca.js:47:24)
    at http://localhost:1234/src.f69400ca.js:81:7
    at http://localhost:1234/src.f69400ca.js:120:3
    ```

**Comment by D1plo1d** [comment]
Submitted a PR at #72
